dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# Dependencies to install
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install --user codecov
  - pip install pytest
# Tests
script:
  - pycodestyle twitter_saver/
  - pytest twitter_saver/tests/
# Code coverage
after_success:
  - codecov